"$schema" = "./node_modules/wrangler/config-schema.json"
name = "sowwwl-xyz"
account_id = "299c02ddf7e0d349c5e57b0bfe07a230"
main = "worker.js"
compatibility_date = "2026-04-17"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[routes]]
pattern = "sowwwl.xyz/*"

[[routes]]
pattern = "www.sowwwl.xyz/*"

[[durable_objects.bindings]]
name = "STORAGE"
class_name = "Storage"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "Storage" ]
