ServerTokens Prod
ServerSignature Off
TraceEnable Off
Timeout 3600
LimitRequestBody 0
RequestReadTimeout header=20-40,minrate=500 body=0
SetEnvIf X-Forwarded-Proto https HTTPS=on

<Directory /var/www/html>
    Options -Indexes
    AllowOverride All
    Require all granted
</Directory>

Header always unset X-Powered-By
